version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  web:
    image: php-apache-mysql
    container_name: php_web
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:80"